// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Productos.API.Data;

#nullable disable

namespace Productos.API.Migrations
{
    [DbContext(typeof(ProductosDbContext))]
    [Migration("20260408040654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Productos.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "P001",
                            Nombre = "Laptop HP 15\"",
                            Precio = 850m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "P002",
                            Nombre = "Mouse inalámbrico",
                            Precio = 25m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "P003",
                            Nombre = "Teclado mecánico",
                            Precio = 75m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "P004",
                            Nombre = "Monitor 24\"",
                            Precio = 320m,
                            Stock = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
